name: Create Release

on:
  push:
    tags: v*.*.**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository 📥

      - run: cargo build --release --verbose
        name: Build 🔨

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts ⬆️
        with:
          name: build-${{ matrix.os }}
          path: |
            target/release/bvm
            target/release/bvm-shim
            target/release/bvm.exe
            target/release/bvm-shim.exe

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository 📥

      # We can pass --no-verify here as the build is already verified with the previous job
      - run: cargo publish --no-verify --token ${CRATES_TOKEN}
        name: Publish on Crates.io 📦
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download Artifacts ⬇️
        id: download_artifact
        with:
          path: release/
          pattern: build-*
          merge-multiple: true

      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        name: Create Release Draft 📝
        id: create_release
        with:
          draft: true
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: shogo82148/actions-upload-release-asset@c91b7fd867cf280772374042252f0dc8e1ade751
        name: Upload binaries ⬆️📦
        with:
          asset_path: ${{ steps.download_artifact.outputs.download-path }}/bvm*
          upload_url: ${{ steps.create_release.outputs.upload_url }}
